spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        user_ban_channel:
          name: user_ban
        follower_channel:
          name: follower_channel
        profile_view_channel:
          name: profile_view_channel
        premium-bought-channel:
          name: premium_bought

server:
  port: 8080

project-service:
  host: localhost
  port: 8082

payment-service:
  host: localhost
  port: 9080
  endpoint: /api/payment

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    endpoint: http://127.0.0.1:9000
    accessKey: user
    secretKey: password
    bucketName: user-service-bucket

  dicebear:
    avatar: https://api.dicebear.com/8.x/pixel-art/svg?seed=
    small_avatar: https://api.dicebear.com/8.x/pixel-art/svg?size=100&seed=

scheduler:
  premium-remover: "@weekly"
  cron-expression-weekly: "0 0 0 * * ?"
  cron-expression-daily: "0 0 0 * * *"

event:
  past:
    delete-batch: 100

premium:
  expired:
    delete-batch: 200

thread-pool:
  thread-count: 10

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB